### ISSUE TITLE
Error during cleanup after a failed test run

### ISSUE THREAD

**Issue by wallrj** [jetstack/test-infra#52]
```
I1113 16:58:42.815] Makefile:38: recipe for target '.run_e2e' failed
I1113 16:58:42.868] Deleting local Kubernetes cluster...
I1113 16:58:43.618] Machine deleted.
W1113 16:58:43.626] Traceback (most recent call last):
W1113 16:58:43.626]   File "/workspace/./test-infra/jenkins/../scenarios/minikube.py", line 62, in <module>
W1113 16:58:43.626]     main(ARGS.env, ARGS.cmd + ARGS.args)
W1113 16:58:43.626]   File "/workspace/./test-infra/jenkins/../scenarios/minikube.py", line 53, in main
W1113 16:58:43.626]     check(*cmd)
W1113 16:58:43.627]   File "/workspace/./test-infra/jenkins/../scenarios/minikube.py", line 43, in check
W1113 16:58:43.627]     raise exception
W1113 16:58:43.627] TypeError: __init__() takes at least 3 arguments (1 given)
E1113 16:58:43.627] Command failed
I1113 16:58:43.627] process 405 exited with code 1 after 8.5m
E1113 16:58:43.627] FAIL: navigator-e2e-v1-7

```

Full log:
 * https://prow.build-infra.jetstack.net/log?job=navigator-e2e-v1-7&id=33
 * [log.txt](https://github.com/jetstack/test-infra/files/1467724/log.txt)

**Comment by wallrj** [comment]
Another example: https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_navigator/143/navigator-e2e-v1-8/151/
